#!/bin/bash

source "$HOME/.config/polybar/scripts/env.sh"

export COLOR_BACKGROUND=$COLOR_BACKGROUND
export COLOR_BACKGROUND_ALT=$COLOR_BACKGROUND_ALT
export COLOR_FOREGROUND=$COLOR_FOREGROUND
export COLOR_PRIMARY=$COLOR_PRIMARY
export COLOR_SECONDARY=$COLOR_SECONDARY
export COLOR_TERTIARY=$COLOR_TERTIARY
export COLOR_DISABLED=$COLOR_DISABLED
export COLOR_ACTIVE=$COLOR_ACTIVE
export COLOR_URGENT=$COLOR_URGENT

pkill polybar
polybar -q bar &
