#!/usr/bin/env bash

source "$HOME/scripts/polybar/env.sh"

export COLOR_BACKGROUND="#CC${COLOR_BACKGROUND#\#}"
export COLOR_BACKGROUNDALT=$COLOR_BACKGROUNDALT
export COLOR_FOREGROUND=$COLOR_FOREGROUND
export COLOR_PRIMARY=$COLOR_PRIMARY
export COLOR_SECONDARY=$COLOR_SECONDARY
export COLOR_DISABLED=$COLOR_DISABLED
export COLOR_ACTIVE=$COLOR_ACTIVE
export COLOR_ALERT=$COLOR_ALERT

pkill polybar
polybar bar &
